import type {
  Brand,
  Category,
  Product,
  ProductImage,
  Order,
  OrderItem,
  Customer,
  Review,
  HomepageSection,
  Page,
  Discount,
  Coupon,
  PromotionalBanner,
  InventoryLog,
  AuditLog,
  StoreSetting,
} from "@/types/domain.types";
import { loadPersistedStore } from "@/lib/persistence";

// Load previously saved data from disk (survives server restarts & reboots)
const _saved = loadPersistedStore();

// ---------------------------------------------------------------------------
// Global singleton stores – shared across ALL Next.js server workers/requests
// so that any mutation (add/edit/delete) in a Server Action is immediately
// visible to admin Server Components that run in a different worker context.
// ---------------------------------------------------------------------------
declare global {
  // eslint-disable-next-line no-var
  var __DEMO_BRANDS: Brand[];
  // eslint-disable-next-line no-var
  var __DEMO_CATEGORIES: Category[];
  // eslint-disable-next-line no-var
  var __DEMO_PRODUCT_IMAGES: ProductImage[];
  // eslint-disable-next-line no-var
  var __DEMO_PRODUCTS: Product[];
  // eslint-disable-next-line no-var
  var __DEMO_REVIEWS: Review[];
  // eslint-disable-next-line no-var
  var __DEMO_HOMEPAGE_SECTIONS: HomepageSection[];
  // eslint-disable-next-line no-var
  var __DEMO_PAGES: Page[];
  // eslint-disable-next-line no-var
  var __DEMO_DISCOUNTS: Discount[];
  // eslint-disable-next-line no-var
  var __DEMO_COUPONS: Coupon[];
  // eslint-disable-next-line no-var
  var __DEMO_BANNERS: PromotionalBanner[];
  // eslint-disable-next-line no-var
  var __DEMO_CUSTOMERS: Customer[];
  // eslint-disable-next-line no-var
  var __DEMO_ORDERS: Order[];
  // eslint-disable-next-line no-var
  var __DEMO_STORE_SETTINGS: StoreSetting[];
}

const now = new Date().toISOString();

// ---------------------------------------------------------------------------
// Brands
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_BRANDS) {
  const saved = (_saved?.brands as Brand[] | undefined);
  globalThis.__DEMO_BRANDS = saved && saved.length > 0 ? saved : [
    {
      id: "c0000000-0000-0000-0000-000000000001",
      name: "Dior",
      slug: "dior",
      description: "French luxury beauty house",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 1,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000002",
      name: "Chanel",
      slug: "chanel",
      description: "Timeless French elegance",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 2,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000003",
      name: "La Mer",
      slug: "la-mer",
      description: "Miracle broth skincare",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000004",
      name: "Tom Ford Beauty",
      slug: "tom-ford-beauty",
      description: "Modern luxury beauty",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 4,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000005",
      name: "ANUA",
      slug: "anua",
      description: "Korean skincare brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 5,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000006",
      name: "Memwa",
      slug: "memwa",
      description: "Body mist and fragrance brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 6,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000007",
      name: "Parachute",
      slug: "parachute",
      description: "India's No.1 coconut oil brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 7,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000008",
      name: "Balea",
      slug: "balea",
      description: "German personal care brand by dm",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 8,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000009",
      name: "Velvet",
      slug: "velvet",
      description: "Luxury body butter brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 9,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000010",
      name: "Ebelin",
      slug: "ebelin",
      description: "German beauty accessories by dm",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 10,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000011",
      name: "Kesh King",
      slug: "kesh-king",
      description: "Ayurvedic hair care by Emami",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 11,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000012",
      name: "The Ordinary",
      slug: "the-ordinary",
      description: "Clinical skincare by DECIEM",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 12,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000013",
      name: "Teresia",
      slug: "teresia",
      description: "Korean collagen skincare",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 13,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000014",
      name: "Watsons",
      slug: "watsons",
      description: "Personal care and beauty brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 14,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000015",
      name: "Farmstay",
      slug: "farmstay",
      description: "Korean sun care and skincare",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 15,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000016",
      name: "Godrej",
      slug: "godrej",
      description: "Indian FMCG and beauty brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 16,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000017",
      name: "Super Kids",
      slug: "super-kids",
      description: "Kids hair care brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 17,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000018",
      name: "Vaseline",
      slug: "vaseline",
      description: "Intensive care body brand by Unilever",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 18,
      created_at: now,
      updated_at: now,
    },
    {
      id: "c0000000-0000-0000-0000-000000000019",
      name: "Jam Tint",
      slug: "jam-tint",
      description: "Korean lip tint brand",
      logo_url: null,
      banner_url: null,
      meta_title: null,
      meta_description: null,
      is_active: true,
      sort_order: 19,
      created_at: now,
      updated_at: now,
    },
  ] as Brand[];
}
export const DEMO_BRANDS: Brand[] = globalThis.__DEMO_BRANDS;

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_CATEGORIES) {
  const saved = (_saved?.categories as Category[] | undefined);
  globalThis.__DEMO_CATEGORIES = saved && saved.length > 0 ? saved : [
    {
      id: "d0000000-0000-0000-0000-000000000001",
      name: "Skincare",
      slug: "skincare",
      description: "Premium skincare products",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 1,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000002",
      name: "Makeup",
      slug: "makeup",
      description: "Luxury makeup collection",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 2,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000003",
      name: "Fragrance",
      slug: "fragrance",
      description: "Exclusive fragrances",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 3,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000004",
      name: "Serums",
      slug: "serums",
      description: "Targeted treatment serums",
      image_url: null,
      parent_id: "d0000000-0000-0000-0000-000000000001",
      meta_title: null,
      meta_description: null,
      sort_order: 1,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000005",
      name: "Moisturizers",
      slug: "moisturizers",
      description: "Hydrating moisturizers",
      image_url: null,
      parent_id: "d0000000-0000-0000-0000-000000000001",
      meta_title: null,
      meta_description: null,
      sort_order: 2,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000006",
      name: "Lipstick",
      slug: "lipstick",
      description: "Luxury lip colors",
      image_url: null,
      parent_id: "d0000000-0000-0000-0000-000000000002",
      meta_title: null,
      meta_description: null,
      sort_order: 1,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000007",
      name: "Deodorants",
      slug: "deodorants",
      description: "مزيلات العرق والمعطرات",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 4,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000008",
      name: "Body Care",
      slug: "body-care",
      description: "العناية بالجسم",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 5,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000009",
      name: "Hair Care",
      slug: "hair-care",
      description: "العناية بالشعر",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 6,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "d0000000-0000-0000-0000-000000000010",
      name: "Sunscreen",
      slug: "sunscreen",
      description: "واقيات الشمس والحماية من الأشعة الضارة",
      image_url: null,
      parent_id: null,
      meta_title: null,
      meta_description: null,
      sort_order: 7,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ] as Category[];
}
export const DEMO_CATEGORIES: Category[] = globalThis.__DEMO_CATEGORIES;

// ---------------------------------------------------------------------------
// Product Images
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_PRODUCT_IMAGES) {
  const saved = (_saved?.productImages as ProductImage[] | undefined);
  globalThis.__DEMO_PRODUCT_IMAGES = saved && saved.length > 0 ? saved : [
    {
      id: "img-001",
      product_id: "f0000000-0000-0000-0000-000000000001",
      url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
      alt_text: "Capture Totale Serum",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-002",
      product_id: "f0000000-0000-0000-0000-000000000002",
      url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
      alt_text: "Crème de la Mer",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-003",
      product_id: "f0000000-0000-0000-0000-000000000003",
      url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
      alt_text: "Rouge Allure Velvet",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-004",
      product_id: "f0000000-0000-0000-0000-000000000004",
      url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800",
      alt_text: "Black Orchid",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-005",
      product_id: "f0000000-0000-0000-0000-000000000005",
      url: "https://images.unsplash.com/photo-1617897903246-719242758050?w=800",
      alt_text: "Prestige Le Nectar",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-006",
      product_id: "f0000000-0000-0000-0000-000000000006",
      url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800",
      alt_text: "The Concentrate",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-007",
      product_id: "f0000000-0000-0000-0000-000000000007",
      url: "/uploads/anua-niacinamide-10-txa-4-serum-30ml.jpeg",
      alt_text: "ANUA Niacinamide 10 + TXA 4 Serum",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-008",
      product_id: "f0000000-0000-0000-0000-000000000008",
      url: "/uploads/memwa-body-mist-musk-al-tahara.jpg",
      alt_text: "Memwa Body Mist Musk Al Tahara",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-009",
      product_id: "f0000000-0000-0000-0000-000000000009",
      url: "/uploads/parachute-coconut-oil-200ml.jpg",
      alt_text: "Parachute Coconut Oil 200ml",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-010",
      product_id: "f0000000-0000-0000-0000-000000000010",
      url: "/uploads/balea-parfum-deodorant-glamorous-moment.jpg",
      alt_text: "Balea Parfum Deodorant Glamorous Moment",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-011",
      product_id: "f0000000-0000-0000-0000-000000000011",
      url: "/uploads/balea-sensitive-deocreme.jpg",
      alt_text: "Balea Sensitive Deocreme",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-012",
      product_id: "f0000000-0000-0000-0000-000000000012",
      url: "/uploads/jam-tint-soft-lipstick-06.jpg",
      alt_text: "Jam Tint Soft Lipstick No.06",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-013",
      product_id: "f0000000-0000-0000-0000-000000000013",
      url: "/uploads/blush-compact-red-02.jpg",
      alt_text: "Blush Compact No.2 Red",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-014",
      product_id: "f0000000-0000-0000-0000-000000000014",
      url: "/uploads/velvet-body-butter-strawberry-cheesecake.jpg",
      alt_text: "Velvet Body Butter Strawberry Cheesecake",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-015",
      product_id: "f0000000-0000-0000-0000-000000000015",
      url: "/uploads/ebelin-styling-kamm.jpg",
      alt_text: "Ebelin Styling Kamm Bio",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-016",
      product_id: "f0000000-0000-0000-0000-000000000016",
      url: "/uploads/kesh-king-organic-onion-shampoo.jpg",
      alt_text: "Kesh King Organic Onion Shampoo",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-017",
      product_id: "f0000000-0000-0000-0000-000000000017",
      url: "/uploads/velvet-body-butter-musc-poudree.jpg",
      alt_text: "Velvet Body Butter Musc Poudrée",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-018",
      product_id: "f0000000-0000-0000-0000-000000000018",
      url: "/uploads/the-ordinary-glycolic-acid-7-toning-solution.jpg",
      alt_text: "The Ordinary Glycolic Acid 7% Toning Solution",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-019",
      product_id: "f0000000-0000-0000-0000-000000000019",
      url: "/uploads/teresia-marine-collagen-brightening-cream.jpg",
      alt_text: "Teresia Marine Collagen Brightening Cream",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-020",
      product_id: "f0000000-0000-0000-0000-000000000020",
      url: "/uploads/balea-parfum-deodorant-golden-moon.jpg",
      alt_text: "Balea Parfum Deodorant Golden Moon",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-021",
      product_id: "f0000000-0000-0000-0000-000000000021",
      url: "/uploads/godrej-nupur-henna.jpg",
      alt_text: "Godrej Nupur Henna 100% Pure",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-022",
      product_id: "f0000000-0000-0000-0000-000000000022",
      url: "/uploads/farmstay-oil-free-sun-cream.jpg",
      alt_text: "Farmstay Oil-Free UV Defence Sun Cream SPF50+",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-023",
      product_id: "f0000000-0000-0000-0000-000000000023",
      url: "/uploads/balea-parfum-deodorant-pure-elegance.jpg",
      alt_text: "Balea Parfum Deodorant Pure Elegance",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-024",
      product_id: "f0000000-0000-0000-0000-000000000024",
      url: "/uploads/watsons-so-sexy-deodorant.jpg",
      alt_text: "Watsons So Sexy Deodorant",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-025",
      product_id: "f0000000-0000-0000-0000-000000000025",
      url: "/uploads/balea-deocreme-himbeer-magnolien.jpg",
      alt_text: "Balea Deocreme Himbeer & Magnolien",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-026",
      product_id: "f0000000-0000-0000-0000-000000000026",
      url: "/uploads/super-kids-hair-cream.jpg",
      alt_text: "Super Kids Hair Cream",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-027",
      product_id: "f0000000-0000-0000-0000-000000000027",
      url: "/uploads/balea-parfum-deodorant-blossom.jpg",
      alt_text: "Balea Parfum Deodorant Blossom",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
    {
      id: "img-028",
      product_id: "f0000000-0000-0000-0000-000000000028",
      url: "/uploads/vaseline-vitamin-b3-body-oil-200ml.jpg",
      alt_text: "Vaseline Vitamin B3 Body Oil 200ml",
      sort_order: 0,
      is_primary: true,
      created_at: now,
    },
  ] as ProductImage[];
}
export const DEMO_PRODUCT_IMAGES: ProductImage[] =
  globalThis.__DEMO_PRODUCT_IMAGES;

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_PRODUCTS) {
  const saved = (_saved?.products as Product[] | undefined);
  globalThis.__DEMO_PRODUCTS = saved && saved.length > 0 ? saved : [
    {
      id: "f0000000-0000-0000-0000-000000000001",
      name: "Capture Totale Super Potent Serum",
      slug: "capture-totale-serum",
      description:
        "An extraordinary anti-aging serum that rejuvenates skin from within.",
      short_description: "Anti-aging serum for youthful radiance",
      brand_id: "c0000000-0000-0000-0000-000000000001",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000004",
      sku: "DIOR-SERUM-001",
      price: 185,
      compare_at_price: 220,
      stock_quantity: 45,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 5,
      review_count: 1,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: true,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000002",
      name: "Crème de la Mer",
      slug: "creme-de-la-mer",
      description: "The iconic moisturizer born from the sea.",
      short_description: "Legendary moisturizing cream",
      brand_id: "c0000000-0000-0000-0000-000000000003",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000005",
      sku: "LAMER-CREAM-001",
      price: 380,
      compare_at_price: null,
      stock_quantity: 30,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 5,
      review_count: 1,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000003",
      name: "Rouge Allure Velvet",
      slug: "rouge-allure-velvet",
      description: "Intense color and comfort in a powdery matte finish.",
      short_description: "Matte lipstick with intense color",
      brand_id: "c0000000-0000-0000-0000-000000000002",
      category_id: "d0000000-0000-0000-0000-000000000002",
      subcategory_id: "d0000000-0000-0000-0000-000000000006",
      sku: "CHANEL-LIP-001",
      price: 45,
      compare_at_price: null,
      stock_quantity: 100,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 4,
      review_count: 1,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000004",
      name: "Black Orchid Eau de Parfum",
      slug: "black-orchid-edp",
      description: "A luxurious and sensual fragrance of rich dark accords.",
      short_description: "Iconic luxury fragrance",
      brand_id: "c0000000-0000-0000-0000-000000000004",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "TF-FRAG-001",
      price: 165,
      compare_at_price: 195,
      stock_quantity: 25,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: true,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000005",
      name: "Prestige Le Nectar",
      slug: "prestige-le-nectar",
      description: "Ultimate regeneration for exceptional skin.",
      short_description: "Premium regeneration nectar",
      brand_id: "c0000000-0000-0000-0000-000000000001",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000005",
      sku: "DIOR-NEC-001",
      price: 420,
      compare_at_price: null,
      stock_quantity: 15,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000006",
      name: "The Concentrate",
      slug: "the-concentrate",
      description: "Powerful serum with Miracle Broth.",
      short_description: "Concentrated healing serum",
      brand_id: "c0000000-0000-0000-0000-000000000003",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000004",
      sku: "LAMER-CON-001",
      price: 295,
      compare_at_price: 350,
      stock_quantity: 20,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: true,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000007",
      name: "ANUA Niacinamide 10 + TXA 4 Serum 30ml",
      slug: "anua-niacinamide-10-txa-4-serum-30ml",
      description: "سيروم نياسيناميد 10% مع TXA 4% لعلاج التصبغات والبقع الداكنة واسمرار الشمس وآثار الحبوب القديمة. خالٍ من العطور، يفتح ويوحد لون البشرة مع ترطيب ونضارة فائقة.",
      short_description: "سيروم تفتيح وتوحيد لون البشرة",
      brand_id: "c0000000-0000-0000-0000-000000000005",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000004",
      sku: "ANUA-SERUM-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000008",
      name: "Memwa Body Mist - Musk Al Tahara Cotton Candy",
      slug: "memwa-body-mist-musk-al-tahara",
      description: "بودي ميست مسك الطهارة بعطر غزل البنات من ميموا. رائحة ناعمة ومنعشة تدوم طويلاً، مثالي للاستخدام اليومي.",
      short_description: "بودي ميست مسك الطهارة غزل البنات",
      brand_id: "c0000000-0000-0000-0000-000000000006",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "MEMWA-MIST-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000009",
      name: "Parachute 100% Pure & Natural Coconut Oil 200ml",
      slug: "parachute-coconut-oil-200ml",
      description: "زيت جوز الهند الطبيعي 100% من باراشوت. الأكثر مبيعاً في الهند لترطيب وتغذية الشعر والبشرة بعمق.",
      short_description: "زيت جوز الهند الطبيعي النقي 200 مل",
      brand_id: "c0000000-0000-0000-0000-000000000007",
      category_id: "d0000000-0000-0000-0000-000000000009",
      subcategory_id: null,
      sku: "PARA-OIL-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000010",
      name: "Balea Parfum Deodorant - Glamorous Moment",
      slug: "balea-parfum-deodorant-glamorous-moment",
      description: "مزيل عرق بارفوم من باليا بعطر شرقي زهري فاخر. 0% ألومنيوم، نباتي 100%، حماية تدوم 24 ساعة مع رائحة أنثوية ساحرة.",
      short_description: "مزيل عرق بعطر شرقي زهري فاخر",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "BALEA-DEO-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000011",
      name: "Balea Sensitive Deocreme 48h",
      slug: "balea-sensitive-deocreme-48h",
      description: "كريم مزيل عرق للبشرة الحساسة من باليا. 0% ألومنيوم، بدون كحول، حماية فعالة تدوم 48 ساعة. نباتي ولطيف على البشرة.",
      short_description: "كريم مزيل عرق للبشرة الحساسة 48 ساعة",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000007",
      subcategory_id: null,
      sku: "BALEA-DEO-002",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000012",
      name: "Jam Tint Soft Lipstick No.06",
      slug: "jam-tint-soft-lipstick-06",
      description: "تنت شفايف ناعم بلون وردي طبيعي يدوم طويلاً. تركيبة كريمية خفيفة تمنح شفاهك لوناً حيوياً ومظهراً مخملياً.",
      short_description: "تنت شفايف ناعم بلون وردي طبيعي",
      brand_id: "c0000000-0000-0000-0000-000000000019",
      category_id: "d0000000-0000-0000-0000-000000000002",
      subcategory_id: "d0000000-0000-0000-0000-000000000006",
      sku: "JAMTINT-LIP-006",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000013",
      name: "Blush Compact No.2 Red",
      slug: "blush-compact-red-02",
      description: "بلاشر مضغوط بدرجة أحمر طبيعي لإطلالة مشرقة ومفعمة بالحيوية. سهل التطبيق ويدوم طويلاً مع مرآة مدمجة.",
      short_description: "بلاشر مضغوط بدرجة أحمر طبيعي",
      brand_id: null,
      category_id: "d0000000-0000-0000-0000-000000000002",
      subcategory_id: null,
      sku: "BLUSH-RED-002",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000014",
      name: "Velvet Body Butter - Strawberry Cheesecake",
      slug: "velvet-body-butter-strawberry-cheesecake",
      description: "بودي بتر فيلفيت بخلاصة الكمأة بعطر ستروبيري تشيز كيك. ميكس فراولة مع فانيليا بعطر شوجري خطير يجنن! ترطيب عميق ونعومة فائقة.",
      short_description: "بودي بتر بعطر ستروبيري تشيز كيك",
      brand_id: "c0000000-0000-0000-0000-000000000009",
      category_id: "d0000000-0000-0000-0000-000000000008",
      subcategory_id: null,
      sku: "VELVET-BB-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000015",
      name: "Ebelin Styling Kamm Bio",
      slug: "ebelin-styling-kamm-bio",
      description: "مشط تصفيف من إيبلين مصنوع من ألياف الخشب الطبيعي والبلاستيك الحيوي. مضاد للكهرباء الساكنة، صديق للبيئة ومثالي لجميع أنواع الشعر.",
      short_description: "مشط تصفيف طبيعي صديق للبيئة",
      brand_id: "c0000000-0000-0000-0000-000000000010",
      category_id: "d0000000-0000-0000-0000-000000000009",
      subcategory_id: null,
      sku: "EBELIN-KAMM-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000016",
      name: "Kesh King Organic Onion Shampoo",
      slug: "kesh-king-organic-onion-shampoo",
      description: "شامبو البصل العضوي من كيش كينج بأوراق الكاري و21 عشبة طبيعية. يقلل تساقط الشعر بنسبة 98%، يعزز النمو، خالٍ من البارابين. يجعل الشعر ناعماً ولامعاً ويمنع الشيب المبكر.",
      short_description: "شامبو البصل العضوي لتقليل التساقط وتعزيز النمو",
      brand_id: "c0000000-0000-0000-0000-000000000011",
      category_id: "d0000000-0000-0000-0000-000000000009",
      subcategory_id: null,
      sku: "KESH-SHAM-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000017",
      name: "Velvet Body Butter - Musc Poudrée",
      slug: "velvet-body-butter-musc-poudree",
      description: "بودي بتر فيلفيت بخلاصة الكمأة بعطر مسك بودريه. عطر هادئ وراقي برائحة مسك فلوري، ترطيب عميق وبشرة حريرية طوال اليوم.",
      short_description: "بودي بتر بعطر مسك بودريه هادئ وراقي",
      brand_id: "c0000000-0000-0000-0000-000000000009",
      category_id: "d0000000-0000-0000-0000-000000000008",
      subcategory_id: null,
      sku: "VELVET-BB-002",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000018",
      name: "The Ordinary Glycolic Acid 7% Toning Solution",
      slug: "the-ordinary-glycolic-acid-7-toning-solution",
      description: "تونر حمض الجليكوليك 7% من ذا أورديناري لتقشير لطيف وتنقية البشرة. يحسن ملمس الجلد ويوحد اللون ويقلل المسام. مناسب للاستخدام المسائي.",
      short_description: "تونر تقشير لطيف بحمض الجليكوليك 7%",
      brand_id: "c0000000-0000-0000-0000-000000000012",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: null,
      sku: "TO-GLYC-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000019",
      name: "Teresia Marine Collagen Brightening Tone Up Cream 50ml",
      slug: "teresia-marine-collagen-brightening-cream",
      description: "كريم تفتيح بالكولاجين البحري من تيريسيا. يوحد لون البشرة ويمنحها إشراقة طبيعية فورية مع ترطيب عميق وحماية من علامات التقدم في السن.",
      short_description: "كريم تفتيح بالكولاجين البحري",
      brand_id: "c0000000-0000-0000-0000-000000000013",
      category_id: "d0000000-0000-0000-0000-000000000001",
      subcategory_id: "d0000000-0000-0000-0000-000000000005",
      sku: "TERESIA-CREAM-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000020",
      name: "Balea Parfum Deodorant - Golden Moon",
      slug: "balea-parfum-deodorant-golden-moon",
      description: "مزيل عرق بارفوم من باليا بعطر شرقي حسي فاخر. 0% ألومنيوم، حماية 24 ساعة مع رائحة شرقية مسائية ساحرة تشبه عطور Mugler Alien.",
      short_description: "مزيل عرق بعطر شرقي حسي فاخر",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "BALEA-DEO-003",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000021",
      name: "Godrej Nupur Henna 100% Pure",
      slug: "godrej-nupur-henna-100-pure",
      description: "حناء نوبور الهندية الطبيعية 100% من جودريج. حناء نقية بدون إضافات كيميائية لتلوين وتقوية الشعر بشكل طبيعي.",
      short_description: "حناء هندية طبيعية 100% نقية",
      brand_id: "c0000000-0000-0000-0000-000000000016",
      category_id: "d0000000-0000-0000-0000-000000000009",
      subcategory_id: null,
      sku: "GODREJ-HENNA-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000022",
      name: "Farmstay Oil-Free UV Defence Sun Cream SPF50+ PA+++",
      slug: "farmstay-oil-free-sun-cream-spf50",
      description: "واقي شمس خالي من الزيوت من فارم ستاي بحماية عالية SPF50+ PA+++. خفيف على البشرة، لا يسبب لمعان، مثالي للبشرة الدهنية والمختلطة.",
      short_description: "واقي شمس خالي من الزيوت SPF50+",
      brand_id: "c0000000-0000-0000-0000-000000000015",
      category_id: "d0000000-0000-0000-0000-000000000010",
      subcategory_id: null,
      sku: "FARM-SUN-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000023",
      name: "Balea Parfum Deodorant - Pure Elegance",
      slug: "balea-parfum-deodorant-pure-elegance",
      description: "مزيل عرق بارفوم من باليا بعطر زهري أنيق يدوم طويلاً. 0% ألومنيوم، رائحة تشبه عطر Chloé الشهير. نباتي 100%.",
      short_description: "مزيل عرق بعطر زهري أنيق يشبه Chloé",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "BALEA-DEO-004",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000024",
      name: "Watsons So Sexy Deodorant 150ml",
      slug: "watsons-so-sexy-deodorant-150ml",
      description: "مزيل عرق بعطر أنثوي جذاب من واتسونز. بدون بودرة، 0% ألومنيوم وبارابين، حماية فعالة تدوم 24 ساعة. 150 مل.",
      short_description: "مزيل عرق أنثوي جذاب بدون ألومنيوم",
      brand_id: "c0000000-0000-0000-0000-000000000014",
      category_id: "d0000000-0000-0000-0000-000000000007",
      subcategory_id: null,
      sku: "WATSONS-DEO-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000025",
      name: "Balea Deocreme - Himbeer & Magnolien 24h",
      slug: "balea-deocreme-himbeer-magnolien",
      description: "كريم مزيل عرق من باليا بصودا الخبز (النترون) بعطر التوت والماغنوليا. 0% ألومنيوم، بدون ميكروبلاستيك، حماية 24 ساعة. عبوة من مواد معاد تدويرها 100%.",
      short_description: "كريم مزيل عرق بعطر التوت والماغنوليا",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000007",
      subcategory_id: null,
      sku: "BALEA-DEO-005",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000026",
      name: "Super Kids Hair Cream",
      slug: "super-kids-hair-cream",
      description: "كريم شعر للأطفال سوبر كيدز لتصفيف سهل وناعم. آمن للاستخدام من عمر سنة فأكثر، يجعل الشعر ناعماً ولامعاً بدون تشابك.",
      short_description: "كريم شعر للأطفال لتصفيف سهل وناعم",
      brand_id: "c0000000-0000-0000-0000-000000000017",
      category_id: "d0000000-0000-0000-0000-000000000009",
      subcategory_id: null,
      sku: "SUPERKIDS-CREAM-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000027",
      name: "Balea Parfum Deodorant - Blossom",
      slug: "balea-parfum-deodorant-blossom",
      description: "مزيل عرق بارفوم من باليا بعطر زهري منعش يدوم طويلاً. 0% ألومنيوم، رائحة تشبه عطر Lancôme La Vie Est Belle. نباتي 100%، حماية 24 ساعة.",
      short_description: "مزيل عرق بعطر زهري منعش يشبه Lancôme",
      brand_id: "c0000000-0000-0000-0000-000000000008",
      category_id: "d0000000-0000-0000-0000-000000000003",
      subcategory_id: null,
      sku: "BALEA-DEO-006",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "f0000000-0000-0000-0000-000000000028",
      name: "Vaseline Intensive Care Vitamin B3 Body Oil 200ml",
      slug: "vaseline-vitamin-b3-body-oil-200ml",
      description: "زيت للجسم بفيتامين B3 من فازلين لبشرة موحدة اللون ومتوهجة. طبيعي 100%، يغذي البشرة بعمق ويمنحها لمعاناً صحياً وإشراقة طبيعية.",
      short_description: "زيت جسم بفيتامين B3 لبشرة متوهجة",
      brand_id: "c0000000-0000-0000-0000-000000000018",
      category_id: "d0000000-0000-0000-0000-000000000008",
      subcategory_id: null,
      sku: "VASELINE-OIL-001",
      price: 0,
      compare_at_price: null,
      stock_quantity: 0,
      low_stock_threshold: 5,
      is_available: true,
      average_rating: 0,
      review_count: 0,
      meta_title: null,
      meta_description: null,
      meta_keywords: null,
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: true,
      is_on_sale: false,
      status: "published",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
  ] as Product[];
}
export const DEMO_PRODUCTS: Product[] = globalThis.__DEMO_PRODUCTS;

// ---------------------------------------------------------------------------
// Reviews
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_REVIEWS) {
  const saved = (_saved?.reviews as Review[] | undefined);
  globalThis.__DEMO_REVIEWS = saved && saved.length > 0 ? saved : [
    {
      id: "rev-001",
      product_id: "f0000000-0000-0000-0000-000000000001",
      customer_id: null,
      reviewer_name: "Sarah M.",
      rating: 5,
      title: "Absolutely transformative",
      content: "My skin has never looked better. Worth every penny.",
      status: "approved",
      created_at: now,
    },
    {
      id: "rev-002",
      product_id: "f0000000-0000-0000-0000-000000000002",
      customer_id: null,
      reviewer_name: "Emma L.",
      rating: 5,
      title: "The holy grail",
      content: "This cream changed my skincare routine forever.",
      status: "approved",
      created_at: now,
    },
    {
      id: "rev-003",
      product_id: "f0000000-0000-0000-0000-000000000003",
      customer_id: null,
      reviewer_name: "Nadia K.",
      rating: 4,
      title: "Beautiful color",
      content: "Gorgeous shade and long-lasting formula.",
      status: "approved",
      created_at: now,
    },
  ] as Review[];
}
export const DEMO_REVIEWS: Review[] = globalThis.__DEMO_REVIEWS;

// ---------------------------------------------------------------------------
// Homepage Sections
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_HOMEPAGE_SECTIONS) {
  const saved = (_saved?.homepageSections as HomepageSection[] | undefined);
  globalThis.__DEMO_HOMEPAGE_SECTIONS = saved && saved.length > 0 ? saved : [
    {
      id: "sec-001",
      section_type: "hero",
      title: "Discover Luxury Beauty",
      config: {
        subtitle: "Curated premium cosmetics & skincare",
        cta_text: "Shop Now",
        cta_link: "/products",
        image_url:
          "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1920",
      },
      sort_order: 1,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "sec-002",
      section_type: "featured_products",
      title: "Featured Products",
      config: { limit: 4, filter: "featured" },
      sort_order: 2,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "sec-003",
      section_type: "featured_brands",
      title: "Our Brands",
      config: { limit: 4 },
      sort_order: 3,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "sec-004",
      section_type: "new_arrivals",
      title: "New Arrivals",
      config: { limit: 4, filter: "new_arrival" },
      sort_order: 4,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "sec-005",
      section_type: "best_sellers",
      title: "Best Sellers",
      config: { limit: 4, filter: "best_seller" },
      sort_order: 5,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: "sec-006",
      section_type: "reviews",
      title: "What Our Customers Say",
      config: { limit: 3 },
      sort_order: 6,
      is_enabled: true,
      starts_at: null,
      ends_at: null,
      created_at: now,
      updated_at: now,
    },
  ] as HomepageSection[];
}
export const DEMO_HOMEPAGE_SECTIONS: HomepageSection[] =
  globalThis.__DEMO_HOMEPAGE_SECTIONS;

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_PAGES) {
  const saved = (_saved?.pages as Page[] | undefined);
  globalThis.__DEMO_PAGES = saved && saved.length > 0 ? saved : [
    {
      id: "page-001",
      title: "عن متجر LOVELY ORDERS",
      slug: "about",
      content:
        "<div className='space-y-4'><h2 className='text-xl font-bold text-gold'>قصتنا ووعدنا لكِ</h2><p className='leading-relaxed text-luxury-muted'>متجر <strong>LOVELY ORDERS</strong> هو وجهتكِ الأولى والأرقى في مصر للحصول على أجود منتجات التجميل، العناية بالبشرة، والعطور العالمية الأصلية 100%. نضمن لكِ خامات فاخرة، وتغليف آمن ومميز يصلكِ حتى باب المنزل.</p></div>",
      meta_title: "عن متجر LOVELY ORDERS | التجميل الفاخر",
      meta_description: "تعرف على متجر LOVELY ORDERS الرائد في مستحضرات التجميل الفاخرة والعناية بالبشرة في مصر",
      status: "active",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "page-002",
      title: "اتصل بنا وخدمة العملاء",
      slug: "contact",
      content:
        "<div className='space-y-4'><h2 className='text-xl font-bold text-gold'>نحن هنا لخدمتكِ دائماً</h2><p className='text-luxury-muted'>يسعدنا تواصلكِ معنا لأي استفسار أو متابعة لطلبكِ:</p><ul className='list-disc pl-5 space-y-2 text-luxury-muted'><li><strong>الهاتف / فودافون كاش:</strong> 01067258266</li><li><strong>خدمة العملاء:</strong> hello@lovelyorders.com</li><li><strong>أوقات العمل:</strong> يومياً من 10 صباحاً حتى 10 مساءً</li></ul></div>",
      meta_title: "اتصل بنا | LOVELY ORDERS",
      meta_description: "تواصل مع فريق خدمة عملاء LOVELY ORDERS",
      status: "active",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "page-003",
      title: "سياسة الشحن والتوصيل (Shipping Policy)",
      slug: "shipping",
      content:
        "<div className='space-y-6'><h2 className='text-2xl font-bold text-gold'>سياسة الشحن والتوصيل الفاخرة</h2><p className='leading-relaxed text-luxury-muted'>في <strong>LOVELY ORDERS</strong>، نحرص على توصيل مشترياتكِ بأعلى مستويات السرعة والأمان والتغليف الفاخر الذي يحفظ سلامة المنتجات.</p><div className='rounded-luxury border border-luxury-border/30 bg-surface-elevated p-4 space-y-3'><h3 className='font-bold text-luxury-white text-lg'>🚚 مواعيد التوصيل:</h3><ul className='list-disc pl-5 text-sm text-luxury-muted space-y-1.5'><li><strong>القاهرة والجيزة:</strong> يتم التوصيل خلال 24 إلى 48 ساعة من تأكيد الطلب.</li><li><strong>باقي المحافظات والمحافظات الساحلية:</strong> يتم التوصيل خلال 2 إلى 4 أيام عمل.</li></ul></div><div className='rounded-luxury border border-luxury-border/30 bg-surface-elevated p-4 space-y-3'><h3 className='font-bold text-luxury-white text-lg'>💳 خيارات الدفع والمعاينة عند الاستلام:</h3><ul className='list-disc pl-5 text-sm text-luxury-muted space-y-1.5'><li><strong>الدفع عند الاستلام (COD):</strong> يمكنكِ معاينة ومراجعة الطرد بحضور مندوب التوصيل قبل السداد.</li><li><strong>فودافون كاش / إنستاباي:</strong> تحويل سريع وآمن على الرقم <strong className='text-gold font-mono'>01067258266</strong> مع تأكيد الشحن الفوري.</li></ul></div></div>",
      meta_title: "سياسة الشحن والتوصيل | LOVELY ORDERS",
      meta_description: "تعرف على مواعيد الشحن والتوصيل المتاحة لجميع محافظات مصر مع خيار الدفع عند الاستلام والمعاينة",
      status: "active",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "page-004",
      title: "سياسة الشحن والتوصيل",
      slug: "shipping-policy",
      content:
        "<div className='space-y-6'><h2 className='text-2xl font-bold text-gold'>سياسة الشحن والتوصيل الفاخرة</h2><p className='leading-relaxed text-luxury-muted'>في <strong>LOVELY ORDERS</strong>، نحرص على توصيل مشترياتكِ بأعلى مستويات السرعة والأمان والتغليف الفاخر الذي يحفظ سلامة المنتجات.</p><div className='rounded-luxury border border-luxury-border/30 bg-surface-elevated p-4 space-y-3'><h3 className='font-bold text-luxury-white text-lg'>🚚 مواعيد التوصيل:</h3><ul className='list-disc pl-5 text-sm text-luxury-muted space-y-1.5'><li><strong>القاهرة والجيزة:</strong> يتم التوصيل خلال 24 إلى 48 ساعة من تأكيد الطلب.</li><li><strong>باقي المحافظات والمحافظات الساحلية:</strong> يتم التوصيل خلال 2 إلى 4 أيام عمل.</li></ul></div><div className='rounded-luxury border border-luxury-border/30 bg-surface-elevated p-4 space-y-3'><h3 className='font-bold text-luxury-white text-lg'>💳 خيارات الدفع والمعاينة عند الاستلام:</h3><ul className='list-disc pl-5 text-sm text-luxury-muted space-y-1.5'><li><strong>الدفع عند الاستلام (COD):</strong> يمكنكِ معاينة ومراجعة الطرد بحضور مندوب التوصيل قبل السداد.</li><li><strong>فودافون كاش / إنستاباي:</strong> تحويل سريع وآمن على الرقم <strong className='text-gold font-mono'>01067258266</strong> مع تأكيد الشحن الفوري.</li></ul></div></div>",
      meta_title: "سياسة الشحن والتوصيل | LOVELY ORDERS",
      meta_description: "تعرف على مواعيد الشحن والتوصيل المتاحة لجميع محافظات مصر مع خيار الدفع عند الاستلام والمعاينة",
      status: "active",
      published_at: now,
      created_at: now,
      updated_at: now,
    },
  ] as Page[];
}
export const DEMO_PAGES: Page[] = globalThis.__DEMO_PAGES;

// ---------------------------------------------------------------------------
// Discounts & Coupons
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_DISCOUNTS) {
  const saved = (_saved?.discounts as Discount[] | undefined);
  globalThis.__DEMO_DISCOUNTS = saved && saved.length > 0 ? saved : [
    {
      id: "disc-001",
      name: "Summer Sale 10%",
      type: "percentage",
      value: 10,
      applies_to: "all",
      target_id: null,
      starts_at: now,
      ends_at: null,
      is_active: true,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ] as Discount[];
}
export const DEMO_DISCOUNTS: Discount[] = globalThis.__DEMO_DISCOUNTS;

if (!globalThis.__DEMO_COUPONS) {
  const saved = (_saved?.coupons as Coupon[] | undefined);
  globalThis.__DEMO_COUPONS = saved && saved.length > 0 ? saved : [
    {
      id: "coup-001",
      code: "LOVELY10",
      discount_id: "disc-001",
      usage_limit: 100,
      usage_count: 0,
      is_active: true,
      expires_at: null,
      created_at: now,
      discount: globalThis.__DEMO_DISCOUNTS[0],
    },
  ] as Coupon[];
}
export const DEMO_COUPONS: Coupon[] = globalThis.__DEMO_COUPONS;

// ---------------------------------------------------------------------------
// Banners
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_BANNERS) {
  const saved = (_saved?.banners as PromotionalBanner[] | undefined);
  globalThis.__DEMO_BANNERS = saved && saved.length > 0 ? saved : [
    {
      id: "ban-001",
      title: "Summer Glow Collection",
      subtitle: "Up to 20% off selected items",
      image_url:
        "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1200",
      link_url: "/collections/summer-glow",
      placement: "homepage",
      sort_order: 1,
      is_active: true,
      starts_at: now,
      ends_at: null,
      created_at: now,
    },
  ] as PromotionalBanner[];
}
export const DEMO_BANNERS: PromotionalBanner[] = globalThis.__DEMO_BANNERS;

// ---------------------------------------------------------------------------
// Customers
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_CUSTOMERS) {
  const saved = (_saved?.customers as Customer[] | undefined);
  globalThis.__DEMO_CUSTOMERS = saved && saved.length > 0 ? saved : [
    {
      id: "cust-001",
      auth_user_id: null,
      full_name: "Mona Hassan",
      phone: "01012345678",
      email: "mona@example.com",
      segment: "returning",
      total_orders: 3,
      total_spent: 650,
      last_order_at: now,
      created_at: now,
      updated_at: now,
    },
  ] as Customer[];
}
export const DEMO_CUSTOMERS: Customer[] = globalThis.__DEMO_CUSTOMERS;

// ---------------------------------------------------------------------------
// Orders
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_ORDERS) {
  const saved = (_saved?.orders as Order[] | undefined);
  globalThis.__DEMO_ORDERS = saved ?? [] as Order[];
}
export const DEMO_ORDERS: Order[] = globalThis.__DEMO_ORDERS;

// ---------------------------------------------------------------------------
// Inventory & Audit Logs (ephemeral – no need to persist across workers)
// ---------------------------------------------------------------------------
export const DEMO_INVENTORY_LOGS: InventoryLog[] = [];
export const DEMO_AUDIT_LOGS: AuditLog[] = [];

// ---------------------------------------------------------------------------
// Store Settings
// ---------------------------------------------------------------------------
if (!globalThis.__DEMO_STORE_SETTINGS) {
  const saved = (_saved?.storeSettings as StoreSetting[] | undefined);
  globalThis.__DEMO_STORE_SETTINGS = saved && saved.length > 0 ? saved : [
    {
      key: "store.name",
      value: "LOVELY ORDERS",
      updated_at: now,
      updated_by: null,
    },
    {
      key: "store.contact",
      value: { phone: "01067258266", email: "hello@lovelyorders.com" },
      updated_at: now,
      updated_by: null,
    },
    {
      key: "payment.vodafone_number",
      value: "01067258266",
      updated_at: now,
      updated_by: null,
    },
    {
      key: "payment.instapay_number",
      value: "01067258266",
      updated_at: now,
      updated_by: null,
    },
  ] as StoreSetting[];
}
export const DEMO_STORE_SETTINGS: StoreSetting[] =
  globalThis.__DEMO_STORE_SETTINGS;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
export function enrichProduct(product: Product): Product {
  const brand = DEMO_BRANDS.find((b) => b.id === product.brand_id) ?? null;
  const category =
    DEMO_CATEGORIES.find((c) => c.id === product.category_id) ?? null;
  const images = DEMO_PRODUCT_IMAGES.filter(
    (img) => img.product_id === product.id
  );

  return { ...product, brand, category, images };
}

export function enrichProducts(products: Product[]): Product[] {
  return products.map(enrichProduct);
}
